# Generated by Django 6.0.4 on 2026-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
