# Generated by Django 6.0.4 on 2026-04-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
