# Generated by Django 6.0.4 on 2026-04-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_profile_picture_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
