# Generated by Django 6.0.4 on 2026-04-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_num_reviews_alter_profile_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialty',
            new_name='specialty_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
