# Generated by Django 6.0.4 on 2026-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_specialty_profile_specialty_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
