# Generated by Django 6.0.4 on 2026-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='selected_plan',
        ),
        migrations.AddField(
            model_name='appointment',
            name='plan_type',
            field=models.CharField(default='Quick Start', max_length=50),
            preserve_default=False,
        ),
    ]
