# Generated by Django 6.0.4 on 2026-04-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_appointment_selected_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='plan_type',
            new_name='plan_name',
        ),
    ]
