# Generated by Django 6.0.4 on 2026-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_type',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('CONSULTATION', 'Consultation')], default='CONSULTATION', max_length=20),
        ),
    ]
