# Generated by Django 6.0.4 on 2026-04-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_message_attachment_message_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_type',
        ),
    ]
