# Generated by Django 6.0.4 on 2026-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_message_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_type',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('CONSULTATION', 'Consultation')], default='CONSULTATION', max_length=20),
        ),
    ]
