# Generated by Django 6.0.4 on 2026-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_message_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_type',
            field=models.CharField(choices=[('SUPPORT', 'Support'), ('CONSULTATION', 'Consultation')], default='SUPPORT', max_length=20),
        ),
    ]
