# Generated by Django 6.0.4 on 2026-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_message_attachment_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('SILVER', 'Silver'), ('GOLDEN', 'Golden')], default='BASIC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('expert', 'Expert')], default='basic', max_length=20),
        ),
    ]
