# Generated by Django 6.0.4 on 2026-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profile_is_premium_profile_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
