# Generated by Django 6.0.4 on 2026-04-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_content_comment_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issues', models.TextField()),
                ('primary_goal', models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MANAGE_ILLNESS', 'Manage Illness'), ('GENERAL_HEALTH', 'General Health')], max_length=50)),
                ('allergies_meds', models.TextField()),
                ('lifestyle', models.CharField(choices=[('SEDENTARY', 'Sedentary'), ('LIGHTLY_ACTIVE', 'Lightly Active'), ('VERY_ACTIVE', 'Very Active')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='core.appointment')),
            ],
        ),
    ]
