# Generated by Django 6.0.4 on 2026-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_patientquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies_meds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('SEDENTARY', 'Sedentary'), ('LIGHTLY_ACTIVE', 'Lightly Active'), ('VERY_ACTIVE', 'Very Active')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MANAGE_ILLNESS', 'Manage Illness'), ('GENERAL_HEALTH', 'General Health')], max_length=50, null=True),
        ),
    ]
