# Generated by Django 6.0.4 on 2026-04-25 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_profile_allergies_meds_profile_health_issues_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('water_intake', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('diet_followed', models.BooleanField(default=False)),
                ('meal_photo', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('user', 'day_number')},
            },
        ),
    ]
