# Generated by Django 6.0.4 on 2026-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_dailyprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprogress',
            old_name='diet_followed',
            new_name='followed_diet',
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='adherence_score',
            field=models.IntegerField(default=0),
        ),
    ]
